Added preRender callback
afenton90/koa-react-router pull request #8
Opened 2017-11-20 20:29 UTC by SathishGovindaraju

2017-11-21 12:02 UTC, coderas approved these changes
joy.

Non-breaking change 👍

2017-11-23 10:42 UTC, afenton90 requested changes
One line comment then this is ready to go 👍

2017-11-23 10:42 UTC, afenton90 commented on README.md
> +Callback function called before rendering `App`. This callback should return a valid component.
Just need to make it clear here that this component can be resolved in a `Promise`

2017-11-23 11:58 UTC, afenton90 approved these changes
Great work! 💯 
Could I request that an example is added in a future PR.

2017-11-23 11:58 UTC, merged